import Link from "next/link";
import { ArrowRight, ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Service, services } from "../data/site";
import { getServiceJourney } from "../data/journey";
import { SectionHeading } from "./Shell";

export function ServiceDetail({ service }: { service: Service }) {
  const Icon = service.icon;
  const path = getServiceJourney(service.slug);
  const related = path.relatedServices.filter((slug) => slug !== service.slug).slice(0, 5);
  return <section className="section service-detail-page"><div className="container"><div className="detail-grid"><div><span className="icon-tile"><Icon size={25} /></span><p className="eyebrow detail-eyebrow">{service.category}</p><h2>{service.title}</h2><p className="detail-lede">{service.detail}</p><div className="detail-actions"><Link href="/diagnostic" className="button button-dark">Check my requirements <ArrowUpRight size={17} /></Link><Link href="/contact" className="text-link">Talk to Sahaciety <ArrowRight size={16} /></Link></div></div><div className="detail-panel"><p className="eyebrow">Who is this for?</p><h3>A useful starting point for {service.audience.toLowerCase()}.</h3><div className="detail-points">{service.bullets.map((bullet) => <div key={bullet}><CheckCircle2 size={18} /><span>{bullet}</span></div>)}</div></div></div><div className="service-detail-sections"><InfoBlock title="What may be involved" items={path.roadmap.slice(0, 4).map((step) => step.title)} /><div className="responsibility-grid detail-responsibilities"><div><strong>Your effort</strong><p>Share accurate information, review documents and respond to the next request.</p></div><div><strong>Sahaciety support</strong><p>Help clarify the path, organise the checklist and coordinate relevant conversations.</p></div><div><strong>Third party / authority</strong><p>Final eligibility, approval, sanction and formal decisions belong to the relevant authority.</p></div></div><div className="detail-document-block"><div><p className="eyebrow">Documents</p><h3>What you may need</h3></div><div className="document-chips">{path.roadmap.flatMap((step) => step.documents).slice(0, 7).map((document) => <span className={`document-${document.status}`} key={document.name}>{document.status === "required" ? "Required" : document.status === "may" ? "May be required" : "Depends"}: {document.name}</span>)}</div><p className="detail-muted">Documents vary by case, eligibility and the relevant provider or authority.</p></div><InfoBlock title="Time and dependencies" items={path.roadmap.slice(0, 3).map((step) => step.timing)} /></div>{related.length > 0 && <div className="related-services-block"><p className="eyebrow">You may also need</p><h2>Connected services for this journey</h2><div className="related-service-grid">{related.map((slug) => <RelatedService slug={slug} key={slug} />)}</div></div>}<div className="detail-next"><div><p className="eyebrow">Next step</p><h2>Check this against your situation.</h2></div><Link href="/diagnostic" className="button button-dark">Check my requirements <ArrowUpRight size={17} /></Link></div></div></section>;
}

function InfoBlock({ title, items }: { title: string; items: string[] }) { return <section className="info-block"><p className="eyebrow">{title}</p><div>{items.map((item, index) => <p key={`${item}-${index}`}><CheckCircle2 size={17} />{item}</p>)}</div></section>; }
function RelatedService({ slug }: { slug: string }) { const service = services.find((candidate) => candidate.slug === slug); if (!service) return null; return <Link href={`/service/${service.slug}`} className="related-service"><span>{service.category}</span><strong>{service.title}</strong><ArrowRight size={16} /></Link>; }

export function ArticleDetail({ category, title, summary }: { category: string; title: string; summary: string }) {
  return <section className="section"><div className="container article-layout"><article><p className="eyebrow">{category}</p><h2>{title}</h2><p className="article-lede">{summary}</p><p>Good decisions begin with a clear view of the situation. Sahaciety knowledge content is designed to help you understand the usual questions, documents and responsibilities before you take a service forward.</p><h3>Start with the facts</h3><p>Use this guide as a conversation starter, not as a substitute for professional or official advice. The right next step depends on your context, eligibility and the evidence available.</p><h3>Turn understanding into action</h3><p>When you are ready, share what you are trying to accomplish. Sahaciety can help connect the question to a relevant service pathway without making promises that have not been verified.</p></article><aside className="article-aside"><p className="eyebrow">Reading this because you need help?</p><h3>Check whether this may fit your situation.</h3><Link href="/diagnostic" className="button button-dark">Check my requirements <ArrowUpRight size={17} /></Link></aside></div></section>;
}