import Link from "next/link";
import { ArrowRight, ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Footer, Header, SectionHeading } from "./Shell";
import { audiences, helpCards, helpSteps, homepageServices, knowledge, participationPaths, whySahaciety } from "../data/site";

export default function Site() {
  return <><Header /><main>
    <section className="simple-hero"><div className="hero-glow" /><div className="container simple-hero-inner"><div className="simple-hero-copy"><p className="eyebrow eyebrow-light">Governance-led services for people, businesses &amp; societies.</p><h1>One trusted ecosystem for people, business &amp; society.</h1><p>From schemes and finance to business, property, compliance and society services - Sahaciety helps you find the right service and get things done.</p><div className="hero-actions"><Link href="/services" className="button button-primary">Explore Services <ArrowUpRight size={17} /></Link><Link href="/ask-sahaciety" className="button button-ghost">Talk to Sahaciety <ArrowRight size={17} /></Link></div></div><div className="hero-visual" aria-hidden="true"><div className="visual-card visual-card-main"><span className="visual-label">Start with what you need</span><strong>One clear next step.</strong><div className="visual-row"><span>Funding</span><span>Business</span></div><div className="visual-row"><span>Property</span><span>Society</span></div></div><div className="visual-card visual-card-accent"><CheckCircle2 size={18} /> Human help when it matters.</div></div></div></section>
    <section className="help-section"><div className="container"><SectionHeading eyebrow="Start here" title="What do you need help with?" intro="Choose a goal and find a simple place to begin." /><div className="help-grid">{helpCards.map(({ title, summary, icon: Icon, href }) => <Link href={href} className="help-card" key={title}><span className="icon-tile"><Icon size={23} /></span><h3>{title}</h3><p>{summary}</p><span className="text-link">Explore <ArrowRight size={16} /></span></Link>)}</div></div></section>
    <section className="section section-soft"><div className="container"><SectionHeading eyebrow="Our services" title="Services that help you move forward" intro="Practical support across the needs that matter to people, businesses and communities." /><div className="simple-service-grid">{homepageServices.map(({ title, summary, items, icon: Icon, href }) => <div className="simple-service-card" key={title}><div className="service-card-heading"><span className="category-icon"><Icon size={21} /></span><div><h3>{title}</h3><p>{summary}</p></div></div><ul>{items.map((item) => <li key={item}><CheckCircle2 size={16} />{item}</li>)}</ul><Link href={href} className="text-link">View services <ArrowUpRight size={16} /></Link></div>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Who we serve" title="Built for the people and communities we serve" /><div className="audience-grid">{audiences.map(([title, summary], index) => <Link href="/solutions" className="audience-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{summary}</p><ArrowUpRight size={17} /></Link>)}</div></div></section>
    <section className="section process-section"><div className="container"><SectionHeading eyebrow="How Sahaciety helps" title="Simple to start. Easy to follow." intro="You bring the need. We help make the next step clear." align="center" /><div className="simple-steps">{helpSteps.map(([title, summary], index) => <div className="simple-step" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{summary}</p></div>)}</div></div></section>
    <section className="section why-section"><div className="container"><SectionHeading eyebrow="Why Sahaciety" title="A more dependable way to get things done." intro="Clear services, responsible connections and support that respects the real context behind every request." /><div className="why-grid">{whySahaciety.map(([title, summary]) => <div className="why-card" key={title}><CheckCircle2 size={21} /><h3>{title}</h3><p>{summary}</p></div>)}</div></div></section>
    <section className="section participation-simple"><div className="container split-section"><div><SectionHeading eyebrow="Participation" title="More than a service. An ecosystem." intro="Use a service today. Become part of the ecosystem tomorrow." /><Link href="/partners" className="button button-dark">Explore participation <ArrowUpRight size={17} /></Link></div><div className="participation-simple-grid">{participationPaths.map(([title, summary, Icon]) => <Link href="/partners" className="participation-simple-card" key={title as string}><Icon size={21} /><h3>{title as string}</h3><p>{summary as string}</p><ArrowUpRight size={16} /></Link>)}</div></div></section>
    <section className="section knowledge-simple"><div className="container"><div className="knowledge-heading"><SectionHeading eyebrow="Knowledge & guides" title="Know before you decide." /><Link href="/knowledge" className="text-link">View all guides <ArrowRight size={17} /></Link></div><div className="knowledge-simple-grid">{knowledge.slice(0, 4).map((article) => <Link href={`/knowledge/${article.slug}`} className="knowledge-simple-card" key={article.slug}><span>{article.category}</span><h3>{article.title}</h3><p>{article.summary}</p><strong>Read guide <ArrowUpRight size={16} /></strong></Link>)}</div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div><p className="eyebrow eyebrow-light">Ready when you are</p><h2>Not sure where to start?</h2><p>Tell Sahaciety what you need. We&apos;ll help you find the right direction.</p></div><div className="hero-actions"><Link href="/services" className="button button-primary">Get Started <ArrowUpRight size={17} /></Link><Link href="/contact" className="button button-ghost">WhatsApp Us <ArrowRight size={17} /></Link></div></div></section>
  </main><Footer /></>;
}
