import Link from "next/link";
import { ArrowRight, ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Footer, Header, SectionHeading } from "./Shell";
import { Bi, BiInline } from "./Bilingual";
import IntentSearch from "./IntentSearch";
import { audiences, helpCards, helpSteps, homepageJourneys, homepageServices, knowledge, participationPaths, trustPrinciples, whySahaciety } from "../data/site";

export default function Site() {
  return <><Header /><main>
    <section className="simple-hero"><div className="hero-glow" /><div className="container simple-hero-inner"><div className="simple-hero-copy"><p className="eyebrow eyebrow-light"><Bi en="Governance-led services for people, businesses &amp; societies." mr="नागरिक, व्यवसाय आणि संस्थांसाठी सुशासन-आधारित सेवा." /></p><h1><Bi en="One trusted ecosystem for people, business &amp; society." mr="लोक, व्यवसाय आणि समाजासाठी एक विश्वासार्ह परिसंस्था." /></h1><p><Bi en="From schemes and finance to business, property, compliance and society services - Sahaciety helps you find the right service and get things done." mr="योजना आणि वित्तापासून व्यवसाय, मालमत्ता, अनुपालन आणि सोसायटी सेवांपर्यंत - साहासोसायटी तुम्हाला योग्य सेवा शोधून काम पूर्ण करण्यास मदत करते." /></p><IntentSearch /><div className="hero-actions"><Link href="/diagnostic" className="button button-primary"><BiInline en="Take the 2-minute assessment" mr="2-मिनिटांचे मूल्यांकन करा" /> <ArrowUpRight size={17} /></Link><Link href="/services" className="button button-ghost"><BiInline en="Browse services" mr="सेवा पहा" /> <ArrowRight size={17} /></Link></div></div><div className="hero-visual" aria-hidden="true"><div className="visual-card visual-card-main"><span className="visual-label"><Bi en="Start with what you need" mr="तुमच्या गरजेपासून सुरुवात करा" /></span><strong><Bi en="One clear next step." mr="एक स्पष्ट पुढील पाऊल." /></strong><div className="visual-row"><span><BiInline en="Funding" mr="निधी" /></span><span><BiInline en="Business" mr="व्यवसाय" /></span></div><div className="visual-row"><span><BiInline en="Property" mr="मालमत्ता" /></span><span><BiInline en="Society" mr="सोसायटी" /></span></div></div><div className="visual-card visual-card-accent"><CheckCircle2 size={18} /> <BiInline en="Human help when it matters." mr="गरजेच्या क्षणी मानवी मदत." /></div></div></div></section>
    <section className="trust-strip"><div className="container trust-items">{trustPrinciples.map(([title, summary, titleMr, summaryMr]) => <div key={title}><strong><Bi en={title} mr={titleMr} /></strong><span><Bi en={summary} mr={summaryMr} /></span></div>)}</div></section>
    <section className="help-section"><div className="container"><SectionHeading eyebrow="Start here" eyebrowMr="इथून सुरुवात करा" title="What are you trying to accomplish?" titleMr="तुम्हाला काय साध्य करायचे आहे?" intro="You do not need to know the name of a service. Choose a goal and we will help show you the path." introMr="सेवेचे नाव माहित असण्याची गरज नाही. एक ध्येय निवडा, आम्ही तुम्हाला मार्ग दाखवू." /><div className="help-grid">{helpCards.map(({ title, summary, titleMr, summaryMr, icon: Icon, path }) => <Link href={`/diagnostic?path=${path}`} className="help-card" key={title}><span className="icon-tile"><Icon size={23} /></span><h3><Bi en={title} mr={titleMr} /></h3><p><Bi en={summary} mr={summaryMr} /></p><span className="text-link"><BiInline en="Find my path" mr="माझा मार्ग शोधा" /> <ArrowRight size={16} /></span></Link>)}</div></div></section>
    <section className="section section-soft"><div className="container"><SectionHeading eyebrow="Our services" eyebrowMr="आमच्या सेवा" title="Services that help you move forward" titleMr="तुम्हाला पुढे नेणाऱ्या सेवा" intro="Practical support across the needs that matter to people, businesses and communities." introMr="लोक, व्यवसाय आणि समुदायांसाठी महत्त्वाच्या गरजांसाठी व्यावहारिक सहाय्य." /><div className="simple-service-grid">{homepageServices.map(({ title, summary, titleMr, summaryMr, items, itemsMr, icon: Icon, href }) => <div className="simple-service-card" key={title}><div className="service-card-heading"><span className="category-icon"><Icon size={21} /></span><div><h3><Bi en={title} mr={titleMr} /></h3><p><Bi en={summary} mr={summaryMr} /></p></div></div><ul>{items.map((item, index) => <li key={item}><CheckCircle2 size={16} /><BiInline en={item} mr={itemsMr[index]} /></li>)}</ul><Link href={href} className="text-link"><BiInline en="View services" mr="सेवा पहा" /> <ArrowUpRight size={16} /></Link></div>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Who we serve" eyebrowMr="आम्ही कोणासाठी काम करतो" title="Built for the people and communities we serve" titleMr="आम्ही सेवा देत असलेल्या लोकांसाठी आणि समुदायांसाठी घडवलेले" /><div className="audience-grid">{audiences.map(([title, summary, titleMr, summaryMr], index) => <Link href="/solutions" className="audience-card" key={title}><span>0{index + 1}</span><h3><Bi en={title} mr={titleMr} /></h3><p><Bi en={summary} mr={summaryMr} /></p><ArrowUpRight size={17} /></Link>)}</div></div></section>
    <section className="section process-section"><div className="container"><SectionHeading eyebrow="How Sahaciety helps" eyebrowMr="साहासोसायटी कशी मदत करते" title="Simple to start. Easy to follow." titleMr="सुरू करणे सोपे. अनुसरण करणे सोपे." intro="You bring the need. We help make the next step clear." introMr="तुम्ही गरज सांगा. आम्ही पुढील पाऊल स्पष्ट करण्यास मदत करतो." align="center" /><div className="simple-steps">{helpSteps.map(([title, summary, titleMr, summaryMr], index) => <div className="simple-step" key={title}><span>0{index + 1}</span><h3><Bi en={title} mr={titleMr} /></h3><p><Bi en={summary} mr={summaryMr} /></p></div>)}</div></div></section>
    <section className="section journey-section"><div className="container"><SectionHeading eyebrow="Connected journeys" eyebrowMr="जोडलेले प्रवास" title="Wherever you are, Sahaciety helps with the next step." titleMr="तुम्ही कुठेही असाल, साहासोसायटी पुढील पावलासाठी मदत करते." intro="The right path looks different for a business, a property decision, a society or a rural enterprise." introMr="व्यवसाय, मालमत्तेचा निर्णय, सोसायटी किंवा ग्रामीण उद्योगासाठी योग्य मार्ग वेगवेगळा असतो." /><div className="journey-cards">{homepageJourneys.map((journey) => <Link href={journey.href} className="journey-card" key={journey.title}><div><span><Bi en={journey.title} mr={journey.titleMr} /></span><ArrowUpRight size={17} /></div><div className="journey-stages">{journey.stages.map((stage, index) => <span key={stage}><b><BiInline en={stage} mr={journey.stagesMr[index]} /></b>{index < journey.stages.length - 1 && <ArrowRight size={14} />}</span>)}</div></Link>)}</div></div></section>
    <section className="section why-section"><div className="container"><SectionHeading eyebrow="Why Sahaciety" eyebrowMr="साहासोसायटी का" title="A more dependable way to get things done." titleMr="काम पूर्ण करण्याचा अधिक विश्वासार्ह मार्ग." intro="Clear services, responsible connections and support that respects the real context behind every request." introMr="स्पष्ट सेवा, जबाबदार संबंध आणि प्रत्येक विनंतीमागील खऱ्या परिस्थितीचा आदर करणारे सहाय्य." /><div className="why-grid">{whySahaciety.map(([title, summary, titleMr, summaryMr]) => <div className="why-card" key={title}><CheckCircle2 size={21} /><h3><Bi en={title} mr={titleMr} /></h3><p><Bi en={summary} mr={summaryMr} /></p></div>)}</div></div></section>
    <section className="section participation-simple"><div className="container split-section"><div><SectionHeading eyebrow="Participation" eyebrowMr="सहभाग" title="More than a service. An ecosystem." titleMr="फक्त सेवा नाही. एक परिसंस्था." intro="Use a service today. Become part of the ecosystem tomorrow." introMr="आज एक सेवा वापरा. उद्या परिसंस्थेचा भाग बना." /><Link href="/partners" className="button button-dark"><BiInline en="Explore participation" mr="सहभाग शोधा" /> <ArrowUpRight size={17} /></Link></div><div className="participation-simple-grid">{participationPaths.map(([title, summary, Icon, titleMr, summaryMr]) => <Link href="/partners" className="participation-simple-card" key={title as string}><Icon size={21} /><h3><Bi en={title as string} mr={titleMr as string} /></h3><p><Bi en={summary as string} mr={summaryMr as string} /></p><ArrowUpRight size={16} /></Link>)}</div></div></section>
    <section className="section knowledge-simple"><div className="container"><div className="knowledge-heading"><SectionHeading eyebrow="Knowledge & guides" eyebrowMr="ज्ञान व मार्गदर्शन" title="Know before you decide." titleMr="निर्णय घेण्यापूर्वी जाणून घ्या." /><Link href="/knowledge" className="text-link"><BiInline en="View all guides" mr="सर्व मार्गदर्शक पहा" /> <ArrowRight size={17} /></Link></div><div className="knowledge-simple-grid">{knowledge.slice(0, 4).map((article) => <Link href={`/knowledge/${article.slug}`} className="knowledge-simple-card" key={article.slug}><span><Bi en={article.category} mr={article.categoryMr} /></span><h3><Bi en={article.title} mr={article.titleMr} /></h3><p><Bi en={article.summary} mr={article.summaryMr} /></p><strong><BiInline en="Read guide" mr="मार्गदर्शक वाचा" /> <ArrowUpRight size={16} /></strong></Link>)}</div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div><p className="eyebrow eyebrow-light"><Bi en="Ready when you are" mr="तुम्ही तयार असाल तेव्हा" /></p><h2><Bi en="Not sure where to start?" mr="कुठून सुरुवात करावी हे माहित नाही?" /></h2><p><Bi en="Tell Sahaciety what you need. We&apos;ll help you find the right direction." mr="साहासोसायटीला तुमची गरज सांगा. आम्ही तुम्हाला योग्य दिशा शोधण्यास मदत करू." /></p></div><div className="hero-actions"><Link href="/services" className="button button-primary"><BiInline en="Get Started" mr="सुरू करा" /> <ArrowUpRight size={17} /></Link><Link href="/contact" className="button button-ghost"><BiInline en="WhatsApp Us" mr="व्हॉट्सअॅप करा" /> <ArrowRight size={17} /></Link></div></div></section>
  </main><Footer /></>;
}
